OBJS := \
	common.o \
	constants.o \
	packet.o \
	server.o \
	sockets.o \
	st_dbg_ip_driver.o \
	stream_dbg.o \
	

DIRS := 

# NOTE: here should be SUB_MAKE_INCLUDE, different from the top Makefile
include $(SUB_MAKE_INCLUDE)